name: BITNAMI images Secure Rehosting

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *" # Runs every day at 00:00 UTC

env:
  REPOSITORY_NAME: ${{ github.repository }}
  TAG_NAME: ${{ github.ref_name }}

jobs:
  transform-bitnami-images:
    name: Transform Bitnami images
    runs-on: ubuntu-latest
    steps:
      - name: Checkout current repository
        uses: actions/checkout@v4

      - name: Login to Github packages
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Transform images
        env:
          SOURCE_TAG_FIELD: APP_VERSION
          TARGET_REGISTRY: ghcr.io/vaggeliskls
          SOURCE_REGISTRY: docker.io/bitnamisecure
          SKOPEO_ARGS_ENV: --all
          SOURCE_IMAGES: gitea,postgresql,redis,kafka,mongodb,rabbitmq,redis,minio,nginx-ingress-controller,nginx,cainjector,cert-manager,cert-manager-webhook
        run: |
          chmod +x ./transfer-bitnami-images.sh
          ./transfer-bitnami-images.sh
        shell: bash
